### ISSUE TITLE
No webpage found for the web adress

### ISSUE THREAD

**Issue by Achrefgharssalli** [revanced/revanced-website#100]
It shows that the web page doesn't exist

**Comment by Achrefgharssalli** [comment]
![Screenshot_20230606-084606](https://github.com/revanced/revanced-website/assets/101552521/7d70fdac-0330-45c8-92d2-0ef2a6543648)

**Comment by Ushie** [comment]
Working on this

**Comment by TerraPlayz** [comment]
Same error

**Comment by CaTeIM** [comment]
> Working on this

For me isn't working.

**Comment by CaTeIM** [comment]
For me isn't working too

**Comment by yegetshalaay** [comment]
Same error

**Comment by Ushie** [comment]
Resolved now
