### ISSUE TITLE
Arabic is important

### ISSUE THREAD

**Issue by AlaaZaitoon** [revanced/revanced-website#105]
Hello,

I am a loyal user of the Revanced manger app and I would like to request you to support the Arabic language in it. It is a great app but it lacks the option of the Arabic language. I think this will make the app more attractive and widespread among the Arabic users. I hope you will take my request into consideration and add the Arabic language in the next update.

Thank you for your attention and understanding.

**Comment by xafn** [comment]
Wrong repo
