### ISSUE TITLE
Social Buttons hiding patches button

### ISSUE THREAD

**Issue by RafaelJust** [ReVanced/revanced-website#107]
The social Buttons are hiding the 'view patches ' button one phones.
![image of buttons hiding](https://github.com/revanced/revanced-website/assets/74719647/e35b7699-2812-4dc5-b188-aa07275afc65)

**Comment by PickleNik** [comment]
#91 fixes this

**Comment by PickleNik** [comment]
#91 no longer fixes this, but #94 should

**Comment by 4vanyek** [comment]
same issue

**Comment by PickleNik** [comment]
[`src/routes/+page.svelte`](https://github.com/ReVanced/revanced-website/blob/main/src/routes/%2Bpage.svelte)
```
	.wrappezoid {
-		height: calc(100vh - 120px);
+		min-height: calc(100vh - 7.5rem);
```

not sure who did this (me, I did this) but they were really silly because setting a fixed height on a container element is a bad idea :3
