### ISSUE TITLE
fix: restore design consistency

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/revanced-website#11]
## Issue

Currently the website uses different assets and a different logo than the current logo and assets for ReVanced and the slogan also differs from the current slogan ReVanced uses.

## Solution

In favour of consistency, use the current assets, logo and slogan of ReVanced.

## Motivation

Consistency is especially important at an early stage of development of a product. If you build on small inconsistencies, at some point it will be difficult to get rid of them. For that reason it is important to remain consistent.

**Comment by PickleNik** [comment]
thems new assets better tho, make a logo vote alrdy 💀 👀

**Comment by oSumAtrIX** [comment]
There is a reason why it didn't happen yet, a poll would still require #11 to be solved.

**Comment by PickleNik** [comment]
> a poll would still require #11 to be solved.

yup, but that way it would be solved for the better and not for the 
<img height="350" width="512" src="https://user-images.githubusercontent.com/31113245/195680396-a9b3dcb1-4e3f-472a-8157-9998cbf7e7a1.png" />

**Comment by PickleNik** [comment]
> There is a reason

what's the reason?

**Comment by oSumAtrIX** [comment]
As previously mentioned, your proposed solution assumes pollong can be done now, which it can not thus the only solution currently is the original one.

**Comment by oSumAtrIX** [comment]
> > There is a reason
> 
> what's the reason?

The reason is off topic for this issue.

**Comment by PickleNik** [comment]
I think #98 fixes this ))0)

**Comment by PickleNik** [comment]
i guess this can be closed unless the new logo still needs to be added, i have no clue how that works with m3
