### ISSUE TITLE
Patching can't be completed

### ISSUE THREAD

**Issue by AlaaZaitoon** [revanced/revanced-website#116]
![Screenshot_20230609_152752_com android chrome](https://github.com/revanced/revanced-website/assets/104227091/7da0808d-3d29-4ce4-9d3d-87e018c98689)

When I get to this step, nothing happens after it, although I update termux and installed it and updated everything and I face this problem with all versions of YT Revanced (I have not tried another application), but this problem is new and not old

**Comment by xafn** [comment]
Wrong repo

**Comment by AlaaZaitoon** [comment]
/

> الريبو الخطأ




> Wrong repo

Yes, what should I do after you close this report? 😒
