### ISSUE TITLE
fix: don't hardcode any links

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-website#138]
## About

Currently, the footer hardcodes a list of social links. Similar issues in other places might exist. 

## Solution

Where possible, the API response should be used, where not possible a site configuration should be used as described in #137

**Comment by zalnaRs** [comment]
What is the api endpoint to get the socials?

**Comment by oSumAtrIX** [comment]
It should be currently present in the API repo. No public API doc is present yet. I'd say introduce the abstraction in the websites API classes & mock until then. Take #137  into consideration if necessary.

**Comment by oSumAtrIX** [comment]
@alexandreteles may be able to give an insight into this

**Comment by alexandreteles** [comment]
> @alexandreteles may be able to give an insight into this

It is going to be api.revanced.app/v2/socials returning, for example:

```json
{
  "socials": {
    "website": "https://revanced.app",
    "github": "https://github.com/revanced",
    "twitter": "https://twitter.com/revancedapp",
    "discord": "https://discord.gg/revanced",
    "reddit": "https://www.reddit.com/r/revancedapp",
    "telegram": "https://t.me/app_revanced",
    "youtube": "https://www.youtube.com/@ReVanced"
  }
}
```

**Comment by alexandreteles** [comment]
> @alexandreteles may be able to give an insight into this

It is going to be api.revanced.app/v2/socials returning, for example:

```json
{
  "socials": {
    "website": "https://revanced.app",
    "github": "https://github.com/revanced",
    "twitter": "https://twitter.com/revancedapp",
    "discord": "https://discord.gg/revanced",
    "reddit": "https://www.reddit.com/r/revancedapp",
    "telegram": "https://t.me/app_revanced",
    "youtube": "https://www.youtube.com/@ReVanced"
  }
}
```
