### ISSUE TITLE
update the app and fix this

### ISSUE THREAD

**Issue by diitzy** [revanced/revanced-website#142]
![Screenshot_20230709-115506](https://github.com/revanced/revanced-website/assets/129337665/3c7ceec9-bc6a-49fa-9517-15e7bad2389e)

![Screenshot_20230709-115458](https://github.com/revanced/revanced-website/assets/129337665/c593d2cf-9bd6-4e0f-b4ea-0986058988e3)

**Comment by diitzy** [comment]
I'm already using version 1.3.8 and the manager app keeps asking me to update to 1.3.8, that's the same version right?

**Comment by reisxd** [comment]
Wrong repository.

**Comment by diitzy** [comment]
> Wrong repository.

whats mean wrong reposity
