### ISSUE TITLE
Bug: Website auto closing after clicking a patch

### ISSUE THREAD

**Issue by ArthurKun21** [ReVanced/revanced-website#145]
1. Go to https://github.com/ReVanced/revanced-patches
2. Click the website https://revanced.app/
3. Deny the Analytics
4. Click the `view patches`
5. Click the `com.reddit.frontpage`

https://github.com/ReVanced/revanced-website/assets/16458204/fc88e953-59ac-4071-9b19-e1a756455d56

But do it slowly, or like waiting for some time the above steps again and the bug won't appear

**Comment by Ushie** [comment]
Please open your Dev Tools and record the "Console" section during the process

**Comment by oSumAtrIX** [comment]
I can not reproduce this either. Use incognito and try on another browser.

**Comment by oSumAtrIX** [comment]
Try in incognito wifh no extension
