### ISSUE TITLE
feat(ReVanced Patches): Add visual illustration/screenshots of patches 

### ISSUE THREAD

**Issue by kazimmt** [ReVanced/revanced-website#148]
## Issue
At revanced.app/patches, only the names and brief descriptions of the patches are visible, lacking a more comprehensive explanation for new users. Consequently, new users may struggle to grasp which patch to choose and the reasons behind their selection.

## Solution
Upon clicking on any patch name, a popup window will appear, providing a detailed explanation accompanied by visual illustrations or screenshots to depict the functionality and effects of the selected patch.

**Comment by oSumAtrIX** [comment]
The website is consuming the patches from the API, it can not host images of patches
