### ISSUE TITLE
[YT Music Issue] Not able to play offline downloaded songs.

### ISSUE THREAD

**Issue by adnansid99** [ReVanced/revanced-website#158]
There are 2issues. It's not automatic downloading my Liked playlist. And if I download the songs manually, I am not able to play that. It's showing Payment required. :(( Can you please make patch for this?

![received_1749918925469103](https://github.com/ReVanced/revanced-website/assets/60623435/ecbaeece-9a46-43be-999e-667a0684c947)

**Comment by kazimmt** [comment]
First of All Downloading Music is a Premium Feature
Second, This is not the right repo to report patches.

**Comment by Axelen123** [comment]
Closing because this is the wrong issue tracker for this
