### ISSUE TITLE
I'm facing shorts button issue in my Revanced app 

### ISSUE THREAD

**Issue by jais960** [ReVanced/revanced-website#170]
![Screenshot_2023-08-14-09-11-43-98_64ef5fc2000c1caa954c114bb372e1d5](https://github.com/ReVanced/revanced-website/assets/139835189/41bcb5e0-ad98-463e-a043-0fd1ca4ab6e2)
See this only shorts name showing not showing shorts videos and when I'm searching anything shorts not showing

**Comment by xafn** [comment]
Wrong repo

**Comment by apapna** [comment]
Why closed atleast reply solution
