### ISSUE TITLE
feat: Add Branding Guidelines in Website

### ISSUE THREAD

**Issue by kazimmt** [ReVanced/revanced-website#177]
### Issue
Currently ReVanced Website doesn't have a brand identity/Guideline section.

### Solution
Add a Brand Identity/Guideline page in website (Link Maybe in footer menu)

@oSumAtrIX I found Duolingo Brand Guidelines are Good Looking
You can take a look at this: https://design.duolingo.com

**Comment by oSumAtrIX** [comment]
Moved to https://github.com/ReVanced/revanced-branding/issues/15
