### ISSUE TITLE
What I have to do with this?

### ISSUE THREAD

**Issue by elkamynante** [ReVanced/revanced-website#184]
Hello friends!
I've installed ReVanced Manager v1.10.3 from revanced.app (before this I've installed another RVX Manager v1.9.7 although I don't understand what to do with 2 different webs and 2 different apps and which is he true Revanced). Anway boh apps seems to do nothing on my phone and I don't know how or what to do anything. The apps (both) are outdated but no update automatically as is configurated! Can you send my some advice please! Greetings!
[Screenshot_2023-09-29-02-32-59-832_app revanced manager flutter](https://github.com/ReVanced/revanced-website/assets/135672675/5831b37e-6a82-4596-aa7e-da2c43a8818d)

**Comment by oSumAtrIX** [comment]
Here you can find how to use ReVanced Manager: https://github.com/revanced/revanced-manager/tree/main/docs

**Comment by elkamynante** [comment]
Thanks for answer but....Better without! I have no time to read 2h to find how to use a simple app! Today the apps are supposed to do their job once installed! No joke!

**Comment by oSumAtrIX** [comment]
Choosers can't be beggars!
