### ISSUE TITLE
Store fonts locally

### ISSUE THREAD

**Issue by topminipie** [ReVanced/revanced-website#187]
Google has a decidedly non-private privacy policy.
I think it would be better in relation to users to use all fonts locally, without any third-party services. (Google)

**Comment by Ushie** [comment]
Isn't this generally worse? there are other sites that definitely use these fonts from the CDN which means they should be cached, loading them locally may be slower

I'm still interested in this, nevertheless

**Comment by Ushie** [comment]
I think this is unnecessary, there is almost no instance where CDN is unavailable and in that case, there is existing fallbacks including the system font

**Comment by oSumAtrIX** [comment]
Cloudflare will be the cdn if the fonts is served from our source
