### ISSUE TITLE
The notification/subscription of my yt account suddenly became empty even though I subscribed a lot. why? is my account banned? please answer my question.

### ISSUE THREAD

**Issue by KGrimrpr200** [ReVanced/revanced-website#188]

**Comment by Ushie** [comment]
This repository revolves around the https://revanced.app, you can join the [discord server](https://revanced.app/discord) for future inquiries

However, make sure to enable Cloud Messaging in Vanced MicroG:
YouTube > Settings > MicroG > Register device > then turn on Cloud Messaging

**Comment by KGrimrpr200** [comment]
It's on, I tried the original YouTube app, there's no subscription or notifications, it just happened now that I've been using Revanced for a long time.
