### ISSUE TITLE
Use monotone Icon Pack in package patches list

### ISSUE THREAD

**Issue by jo-chemla** [ReVanced/revanced-website#189]
Now that the package count for which patches exist keeps increasing, it could be great to use an icon pack in the [patches list](https://revanced.app/patches) `Package` column of the site. Not necessarily something fancy since using original icons could break the consistency of the page, but could use a minimalist, monochrome pack like. Example OSS packs are [LawnIcons](https://github.com/LawnchairLauncher/lawnicons), [simple-icons](https://github.com/simple-icons/simple-icons) or [Arcticons](https://github.com/Donnnno/Arcticons).

What's useful with LawnIcons for example is that [this file](https://github.com/LawnchairLauncher/lawnicons/blob/develop/app/assets/appfilter.xml) does the mapping between package-id and icon drawable. 

Note: Adding ability to sort patches by creation date would also be great, or as described in [this issue thread](https://github.com/ReVanced/revanced-website/issues/159), show new patches by comparing to list of patches in browser localStorage

**Comment by Ushie** [comment]
That's a good idea, we do have a plan to add app icons and app names, but haven't thought about icon packs

**Comment by jo-chemla** [comment]
Good to hear this is in the pipe! Each entry of that LawnIcons [app/assets/appfilter.xml](https://github.com/LawnchairLauncher/lawnicons/blob/develop/app/assets/appfilter.xml) file has entries like these, which therefore reference both icon drawable (usually from svg folder), package id and app name: 
```xml
<item
  component="ComponentInfo{com.vanced.android.apps.youtube.music/com.google.android.apps.youtube.music.activities.MusicActivity}" 
  drawable="vanced_youtube_music" 
  name="Vanced YouTube Music" 
/>

```

**Comment by oSumAtrIX** [comment]
Closing as stale. Create a new issue if necessary.

**Comment by jo-chemla** [comment]
That LawnIcons [appfilter.xml](https://github.com/LawnchairLauncher/lawnicons/blob/develop/app/assets/appfilter.xml) file referencing svg drawables/icons is pretty heavy, above 1MB, but a simple JS/CLI script - example below - could be used to parse only drawables of apps which have at least one patch existing returned by the [/patches/list API](https://api.revanced.app/v4/patches/list). These drawable strings can be used to locate svg icons from the lawnchair [svg folder here](https://github.com/LawnchairLauncher/lawnicons/tree/develop/svgs). 

Something along the lines of: 

```js
patchesListUrl = 'https://api.revanced.app/v4/patches/list'
// fetch to patchesList
packageIds = Array.from(new Set(patchesList.map(
  e => e.compatiblePackages ? Object.keys(e.compatiblePackages) : null
).flat()))


lawnchairXmlUrl = 'https://raw.githubusercontent.com/LawnchairLauncher/lawnicons/refs/heads/develop/app/assets/appfilter.xml'
// fetch to xmlStr
const parser = new DOMParser();
const lawnchairAppXml = parser.parseFromString(xmlStr, "application/xml"); 
nodes = packageIds.map(packageId => Array.from(lawnchairAppXml.getElementsByTagName('item')).find(c => c.getAttribute('component').includes(packageId))) 
drawables = nodes.filter(n => !!n).map(n => n.getAttribute('drawable') ).map(s => s + '.svg')

// These drawables can be extracted from https://github.com/LawnchairLauncher/lawnicons/tree/develop/svgs
```
