### ISSUE TITLE
Was a component library used in this website?

### ISSUE THREAD

**Issue by rishxt** [ReVanced/revanced-website#197]
Was any component library used in this website? If yes then which? It looks like the Material 3 but as far as I know the Material 3 for the web is not released yet.

**Comment by Axelen123** [comment]
No component library was used. Everything was made from scratch

**Comment by oSumAtrIX** [comment]
I think a QoL change would be to switch to a component library eventually for consistency

**Comment by Ushie** [comment]
Currently none are usable, Material Web atm is terrible at most

**Comment by oSumAtrIX** [comment]
What I mean is that this repo would publish its components as a standalone library and use them in the website project

**Comment by rishxt** [comment]
> No component library was used. Everything was made from scratch

That's pretty cool, the UI is amazing.

**Comment by rishxt** [comment]
> What I mean is that this repo would publish its components as a standalone library and use them in the website project

Yeah, that would be great! I really hope they do publish it.
