### ISSUE TITLE
Buffering issue 

### ISSUE THREAD

**Issue by ggafoor** [ReVanced/revanced-website#202]
After playing the video for a while, buffering is experienced halfway through,  
[3ReVanced Extended_v18.35.36_2023-10-08.json](https://github.com/ReVanced/revanced-website/files/13478576/3ReVanced.Extended_v18.35.36_2023-10-08.json)

This file backup the all settings and restore after this problem my face you buffering issue YouTube shorts also working perfectly that time video is buffering.
 
This application name ReVanced Extended version 18.45.41

**Comment by oSumAtrIX** [comment]
This is ReVanced.

**Comment by oSumAtrIX** [comment]
Wherever you got the forked patches from.
