### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by ggafoor** [ReVanced/revanced-website#203]
https://revanced.to/youtube/#download-apk

![Screenshot_2023-11-29-23-41-20-43_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/ReVanced/revanced-website/assets/82312786/36e0fcde-9dff-43b2-961f-443dec1f4cf5)
This website is you really or feke
The website working you under? Please 🙏 reply

**Comment by Julius8900** [comment]
Fake

**Comment by ggafoor** [comment]
> Fake

Ok thanks you how to update YouTube which one is very fast update possible revanced extended or revanced which one? 
And how to update micro letest safe version
How to download patchs

**Comment by oSumAtrIX** [comment]
This is not a support chat. The official website is revanced.app and you can check the [ReVanced Manager](https://github.com/revanced/revanced-manager/tree/main/docs) guide for usage instructions.
