### ISSUE TITLE
Changes required in the "Search for patches" placeholder in patches tab

### ISSUE THREAD

**Issue by RiddhimannM** [ReVanced/revanced-website#224]
Listing down few issues/enhancement ideas for the search for patches placeholder in the patches path based on my observations as an end-user.

PS - This is my first issue as an open source contributor, so please excuse me for mistakes if any :)

- [x] 1. Currently not able to search a keyword containing hyphen {'-'} in it. See video for reference.

https://github.com/ReVanced/revanced-website/assets/84954173/b7552c85-622f-4da4-8715-fac7d1cd9af6

- [ ] 2. The search bar getting disappeared from view while I scroll down the list of patches. Would prefer a better UX layout which will move the searchbar to a location accessible even while scrolling the page.

https://github.com/ReVanced/revanced-website/assets/84954173/adc50a10-9e9d-47e3-9cd3-a5b2fae6ebcf

**Comment by oSumAtrIX** [comment]
1. It looks like a string sanitization problem. In older times the patch names were stripped of the "-" character, so that may be the cause.
2. This would need some semantical changes such as moving the search from the header to the content

**Comment by oSumAtrIX** [comment]
1. is fixed, please reopen an issue for 2.
