### ISSUE TITLE
feat: Event-based theme

### ISSUE THREAD

**Issue by validcube** [ReVanced/revanced-website#226]
This is just a little quirky idea but . . .

Hey, imagine this; tomorrow is 14th February (as of writing) and suddenly the colour accent of our website suddenly turned whoosh into a pink colour accent. Imagine in 1st January the website use a yellowish colour accent.

Imagine on April fool the website changed logo to the old one.

**Comment by oSumAtrIX** [comment]
Not a bad idea. How easy would this be? I think the root colors can be modified programmatically, but some images have the colors hardcoded.

**Comment by madkarmaa** [comment]
> I think the root colors can be modified programmatically

```js
document.documentElement.style.setProperty('--some-css-variable', '#696969')
```
