### ISSUE TITLE
Not loading videos

### ISSUE THREAD

**Issue by JosephJMRG1** [ReVanced/revanced-website#240]
Hello, this last 2 weeks I have experienced a brutal lag when watching videos, I have reinstalled the app, deleted all the data and nothing works. My internet provider (Movistar Fibra) has no problems.
I made a comparison using the regular youtube app and one with revanced extended and it turns out that only revanced extended has the problem of not loading videos.
Any help?

**Comment by Ushie** [comment]
Hi, this repository is only regarding the ReVanced Website. As for the issue you're experiencing, check out https://github.com/ReVanced/revanced-discussions/discussions/1037
