### ISSUE TITLE
suggestion: Add link to crowdin and remove link to website in footer

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-website#242]
It's odd that the website links to itself like this. There's already the tabs at the top of the page. Also, the website isn't a social platform.

![Screenshot 2024-06-03 163403](https://github.com/ReVanced/revanced-website/assets/84587632/e76b624c-4c89-4dc9-a177-86c3676aedcc)

TBH I'm not sure if this is the correct spot to put the link to Crowdin. Maybe it should be on the [Contributors page](https://revanced.app/contributors)

(The crowdin link should also be added to the README on the ReVanced organization homepage and maybe the patches repo)

**Comment by oSumAtrIX** [comment]
The socials list is consumed from the API. It is not something the webpage controls.
