### ISSUE TITLE
Shortcut icons for relevant ReVanced pages overlap "View patches" 

### ISSUE THREAD

**Issue by Marekk2k** [ReVanced/revanced-website#244]
- There is no way to access the "View patches" tab. Each attempt to enter it ends with clicking on a shortcut to one of the social media 
 - The issue occurs in the mobile Chrome browser in v126 version
- Android 14
-  Phone: Galaxy A54
![Screenshot_20240711_004139_Chrome](https://github.com/ReVanced/revanced-website/assets/169854021/d3324962-aeac-446c-96bc-0f0e0519e8a1)

**Comment by Ushie** [comment]
#107
