### ISSUE TITLE
Issues with icons

### ISSUE THREAD

**Issue by madkarmaa** [ReVanced/revanced-website#255]
I've come across some issues while using the `<Button />` component.

- There's a limited choice of icons, which need to be added manually

- The colors of the icons are hardcoded in the SVG code

[I had to modify the `filter` CSS property to make the colors of the icons black/white](https://github.com/ReVanced/revanced-website/pull/254/files#diff-591f218295070c51913726fb03f7dc03f3edb3224c3fff6cfd2ff0481f2434ccR95-R99) because the hardcoded blue-ish color they currently have didn't fit on red/yellow backgrounds.

I think having an icon library is better than the current method, such as [Google font icons](https://fonts.google.com/icons) or [FontAwesome icons](https://fontawesome.com/icons).

A component can be created as well, [I've already made one for my own website](https://github.com/madkarmaa/madkarmaa.github.io/blob/master/src%2Flib%2Fcomponents%2FFAIcon.svelte), it's a really easy solution.

The only downside I can think of is the big size of these CSS files which need to be downloaded by the client.

**Comment by oSumAtrIX** [comment]
Any free icon pack package should work and should replace the current SVG icons.

**Comment by madkarmaa** [comment]
# Component proposal
Addition in `src/lib/types.ts`
```ts
export enum FAIconFamily {
	CLASSIC = 'classic',
	DUOTONE = 'duotone',
	SHARP = 'sharp',
	SHARP_DUOTONE = 'sharp-duotone'
}

export enum FAIconVariant {
	SOLID = 'solid',
	REGULAR = 'regular',
	LIGHT = 'light',
	THIN = 'thin'
}
```
New component `src/lib/components/Icon.svelte`
```svelte
<script lang="ts">
	import { FAIconFamily, FAIconVariant } from '@/types';

	type Family = FAIconFamily | `${FAIconFamily}`;
	type Variant = FAIconVariant | `${FAIconVariant}`;

	type IconOptions =
		| {
				brands: true;
		  }
		| {
				brands?: never;
				family: Family;
				variant: Variant;
		  };

	export let name: string;
	export let options: IconOptions = { family: 'classic', variant: 'solid' };

	const classes: string[] = [`fa-${name}`];

	if (options.brands) classes.push('fa-brands');
	else Object.values(options).forEach((option) => classes.push(`fa-${option}`));
</script>

<i class="{classes.join(' ')} mr-2 h-4 w-4 flex justify-center items-center"></i>
```
_P.S.: there's [FontAwesome](https://fontawesome.com/search) icon files to import. They can be non-premium (or premium, acquired via page inspection 🤐)_

**Comment by oSumAtrIX** [comment]
Doesn't Fa already provide types

**Comment by madkarmaa** [comment]
> Doesn't Fa already provide types

not that I know of, no
