### ISSUE TITLE
Patches section not working

### ISSUE THREAD

**Issue by Plut0nio** [ReVanced/revanced-website#256]
In the Patches section of the website (https://revanced.app/patches), none of the patches or supported apps show up, even when I type something into the search bar. I've tried this on Firefox on both Linux (pictured below) and Windows along with Cromite on Android. Disabling ad-block and/or Enhanced Tracking Protection didn't fix this, at least not in Firefox.

![image](https://github.com/user-attachments/assets/82f1ab97-3d94-4e48-b52f-33d452fa2f8a)

**Comment by oSumAtrIX** [comment]
The api is rate limited,  not sure why though, because CloudFlare should be caching, either way no a website issue

**Comment by Plut0nio** [comment]
> The api is rate limited, not sure why though, because CloudFlare should be caching, either way no a website issue

I was wondering if the API  had something to do with it. I was just using the default (https://api.revanced.app). Do you know of any other alternative API URL that I can try? Thanks.

**Comment by oSumAtrIX** [comment]
https://dev-api.revanced.app which is the deployment for the dev branch, but it seems like there's another issue

**Comment by Plut0nio** [comment]
> https://dev-api.revanced.app which is the deployment for the dev branch, but it seems like there's another issue which causes this problem

Yeah, I just tried that one and it's still not working, at least on Firefox on Linux.

**Comment by oSumAtrIX** [comment]
Seems like the rate limit is caused by the api raising an error. For that reason cloudflare does not save a cache and the api rate limits. One deployment issue though is not rate limiting using the users IP as a key though, that will need to be investigated.
