### ISSUE TITLE
bug: Archived Integrations project is shown on the website

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVanced/revanced-website#262]
When viewing the contributor page it shows the archived Integrations project.

And all the links are also broken, such as patches where it links to https://github.com/revanced-patches when it should be https://github.com/revanced/revanced-patches

**Comment by oSumAtrIX** [comment]
The data source is controlled by the API environment. Removing the repository will hide it from the website. Links are broken because the API does return the full repo URL, but this is once again something that should be looked into the API end.
