### ISSUE TITLE
fix: accessibility

### ISSUE THREAD

**Issue by Axelen123** [ReVanced/revanced-website#34]
Probably more that needs to be done, but here are some things.
- [ ] Add `aria-label` to navigation menu.
- [ ] Keyboard navigation

**Comment by Axelen123** [comment]
Thanks to `position: fixed` being absolutely broken, I had set `overflow: hidden` on the root html element.
This also arrow key **scrolling** is also broken. I need to somehow refocus it to the body. I think it is possible to do this with `<some-element>.focus()`.

**Comment by WadieBenabdouh** [comment]
>  Add aria-label to navigation menu.

is this still needed?

**Comment by Axelen123** [comment]
> > Add aria-label to navigation menu.
> 
> is this still needed?
> 
> edit: I managed to finish the 1st task, check my latest PR.

Thank you

**Comment by RaduBratan** [comment]
> 

By "keyboard navigation", you strictly refer to scrolling with the up and down arrow keys, or do you have something like switching tabs with the left and right arrow keys in mind?

**Comment by PalmDevs** [comment]
> > Keyboard navigation
> 
> By "keyboard navigation", are you strictly referring to scrolling with the up and down arrow keys, or do you have something like switching tabs with the left and right arrow keys in mind?

Navigating with tabs.

**Comment by RaduBratan** [comment]
> > > Keyboard navigation
> > 
> > 
> > By "keyboard navigation", are you strictly referring to scrolling with the up and down arrow keys, or do you have something like switching tabs with the left and right arrow keys in mind?
> 
> Navigating with pressing the TAB key.

Isn't that already possible by default?

**Comment by PalmDevs** [comment]
> > > > Keyboard navigation
> > > 
> > > 
> > > By "keyboard navigation", are you strictly referring to scrolling with the up and down arrow keys, or do you have something like switching tabs with the left and right arrow keys in mind?
> > 
> > Navigating with pressing the TAB key.
> 
> Isn't that already possible by default?

Yes, but in order for it to function well, we may need to add some attributes to elements and maybe implement a few things, like how YouTube has the hidden Skip navigation button for example.

**Comment by RaduBratan** [comment]
> > > > > Keyboard navigation
> > > > 
> > > > 
> > > > By "keyboard navigation", are you strictly referring to scrolling with the up and down arrow keys, or do you have something like switching tabs with the left and right arrow keys in mind?
> > > 
> > > 
> > > Navigating with pressing the TAB key.
> > 
> > 
> > Isn't that already possible by default?
> 
> Yes, but in order for it to function well, we may need to add some attributes to elements and maybe implement a few things, like how YouTube has the hidden Skip navigation button for example.

Oooohh, thank you for the explanation, now I get it. Wouldn't it be cool to also allow users to navigate to a different tab by just clicking the left/right arrow keys? I could implement that.
