### ISSUE TITLE
CSS: page overflows-x

### ISSUE THREAD

**Issue by Sneffel** [revanced/revanced-website#42]
**.gb-container .gb-container-54c166da .alignfull**

this thing here makes the page larger by some pixel, thus making the page scrollable for 2 extra pixels. 
Your Screen Resolution Width: 1728 Height: 819

the problem is at line 343 of https://revanced.io/wp-content/themes/generatepress/assets/css/main.min.css?ver=3.2.4

```
.no-sidebar .entry-content .alignfull {
	margin-left: calc(-100vw / 2 + 100% / 2);
	margin-right: calc(-100vw / 2 + 100% / 2);
	max-width: 100vw;
	width: auto;
}
```

use this instead

```
.no-sidebar .entry-content .alignfull {
	margin-left: calc((-100vw / 2 + 100% / 2) - 10px);
	margin-right: calc((-100vw / 2 + 100% / 2) - 10px);
	max-width: 100vw;
	width: auto;
}
```

**Comment by xafn** [comment]
`revanced.io` is not the official ReVanced website, `revanced.app` is. This repo is hosted currently at https://dev.revanced.app

**Comment by PalmDevs** [comment]
GitHub mobile is so stupid with buttons, sorry. But as afn said, it's no an official website, so I will close this issue now.

**Comment by Sneffel** [comment]
> `revanced.io` is not the official ReVanced website, `revanced.app` is. This repo is hosted currently at https://dev.revanced.app

This webpage is nowhere to be found. I can't find it on DuckDuckGo or on the revanced github page. I always have to come back to this notification. 
Also, why doesn't it work without root?

**Comment by Ushie** [comment]
> This webpage is nowhere to be found. I can't find it on DuckDuckGo or on the revanced github page

as seen by the subdomain, it is in active development and has not yet been released

> Also, why doesn't it work without root? 

what does not work without root? I see nothing related to that in this issue, please find a relevant issue and be more descriptive
