### ISSUE TITLE
real website ?

### ISSUE THREAD

**Issue by Adithyan007hack** [revanced/revanced-website#55]
Is revanced.io the real website or a fake one?

**Comment by Canny1913** [comment]
No. revanced.io is not associated with us.

**Comment by Adithyan007hack** [comment]
Oh no I have installed the app from that website I am going to uninstall it right now

**Comment by Adithyan007hack** [comment]
It looks like a authentic website you should put a disclamer for users installing apps from that website

**Comment by Adithyan007hack** [comment]
And why is revanced.app not up and running and why does it is redirected to GitHub

**Comment by Canny1913** [comment]
Website is still in development.

**Comment by mkielarv2** [comment]
Why isn't this information on top of README?? That website is first result on Google when searching for ReVanced. It may be dangerous for users that are looking into this project.

**Comment by reisxd** [comment]
> Why isn't this information on top of README?? That website is first result on Google when searching for ReVanced. It may be dangerous for users that are looking into this project.

Read what Canny said.

**Comment by oSumAtrIX** [comment]
Because it is the wrong place to add such a notice, especially about a single site. On the same organization page you can see the official link in its dedicated place above.

**Comment by mkielarv2** [comment]
You are right about the single site, however it would be useful to specify that official website is not ready thus any website that claims to be revanced website is fake as of today. It's easy to be mistaken when the unofficial website is well made and also appears above the github project in the search results.

**Comment by reloxx13** [comment]
> Because it is the wrong place to add such a notice, especially about a single site. On the same organization page you can see the official link in its dedicated place above.

it is not as long as the official site is not done, dont transform a mouse to an elephant.    
this is a huge secruity flaw and a oneliner on top until the webpage is ready is not a problem.    
if fake site populate virues youll get a bad reputation too. users are dumb, its hard to find teh info that this .io page is not official.    

Add this warning in ur readme and stop making a drama about nothing.

**Comment by oSumAtrIX** [comment]
If people go to the wrong page they don't go to the GitHub page to begin with, your approach does not work. The website revanced.app is written everywhere where it makes sense. And fyi it's already on the README.

**Comment by reloxx13** [comment]
nothing is on the readme on the first google result for revanced https://github.com/revanced.
a link redirecting to this readme is not helpfull for users, they think its old or wrong and use the 2nd fake page in google results.
