### ISSUE TITLE
fix: Loading Animation alignment

### ISSUE THREAD

**Issue by kazimmt** [ReVanced/revanced-website#57]
Current Loading Animation is not centered on mobile screen. It's a little bit on right side.
![Screenshot_2023-01-02-20-34-44-592_com chrome canary](https://user-images.githubusercontent.com/82371061/210245757-01759b01-0463-4d6b-ba64-6c7ef47a8642.jpg)

https://user-images.githubusercontent.com/82371061/210246049-cee88498-62e3-410c-8f56-593abe081233.mp4

**Comment by niyasrad** [comment]
I've checked on local with the CSS. It's the calculation going wrong with the styling of the position, I'll make a PR with this issue fixed.
