### ISSUE TITLE
Fix: navigation (menu)bar not opening in android browsers

### ISSUE THREAD

**Issue by meetpateltech** [revanced/revanced-website#58]
The site opened in all popular browsers mobile view but navigation bar not working

The upper side navigation menu bar not opening in mobile site using brave/chrome/edge/Firefox android browsers.

**Comment by xafn** [comment]
Can you show a recording of what you are seeing?

**Comment by meetpateltech** [comment]
> Can you show a recording of what you are seeing?


https://user-images.githubusercontent.com/113581962/210832926-4f167b13-269f-407e-842e-d9e5a3a5df12.mp4

**Comment by xafn** [comment]
I don't even know how you came across this link, but the newest dev preview for the site is at [dev.revanced.app](https://dev.revanced.app/). The navbar should work there :)
