### ISSUE TITLE
ci: move to GitHub Pages

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/revanced-website#66]
## Issue 

Currently, the website is deployed to Spheron. The main motivation to move from "GitHub Pages" was not being able to deploy previews of PRs. The motivation for Spheron specifically was that it allowed us to use teams. Unfortunately, by using something different than "GitHub Pages", ReVanced is now dependent on another service. Dependency on services should be avoided. Also, apparently, Spheron has issues with branches as to why the current deployment to `dev.revanced.app` does not work properly.

## Solution

Move deployment back to GitHub Pages. 

## Motivation

The motivation for moving away from GitHub pages is outdated:

- GitHub Pages is natively available on GitHub - a service ReVanced mainly depends on already
- GitHub Pages allows collaboration with teams
- Deploying previews of PRs is possible with [pr-preview](https://github.com/rossjrw/pr-preview-action)

**Comment by xafn** [comment]
Are there any substitutes for preview links for every commit? That comes in handy when troubleshooting between different commits.

**Comment by oSumAtrIX** [comment]
No. Deployments should not be created for each commit. Troubleshooting commits should be done locally generally speaking.

**Comment by xafn** [comment]
It becomes easier because while it may work fine on my local device, it may not with someone using an Samsung S9 with a Firefox browser (and dev tools doesn't perfectly replicate this). It makes it easier to test on different devices.

**Comment by oSumAtrIX** [comment]
I am not sure what the issue is. If you deploy it via CI, you would still have to visit it in your browser. So it does not matter if you deploy it locally or via CI.

**Comment by oSumAtrIX** [comment]
Does Spheron deploy each commit?

**Comment by Ushie** [comment]
I was assigned to this, but I'm unsure what I'm expected to do as I'm not part of the website team

**Comment by oSumAtrIX** [comment]
Whoops looks like missclick, fixed.

**Comment by Coolguy3289** [comment]
Has Cloudflare Pages been considered as an alternative? The repo housing the site and code is already on github which is a compatible source for both prod deployments and PR previews.

**Comment by oSumAtrIX** [comment]
Yes, it has been previously considered and tested, but it does not fulfill the motivation points mentioned in the original issue description

**Comment by Coolguy3289** [comment]
I'm not sure if you guys are using Cloudflare for DNS (recommended), but if you are, then CF Pages would satisfy the motivation points, even more so than GH Pages imo. As mentioned above, CF Pages does deploy PRs so they can be previewed, if you use it for DNS than it's already used by the ReVanced team, and it allows collaboration with teams by both utilizing code uploaded to the Github repo, AND adding people to the CF account as they are trusted with that access.

**Comment by Ushie** [comment]
We're going to go with GH Pages due to the fact that our teams are already here on GitHub, it would require no extra setup for team and no new platform to have to deal with for frontend

as for reviews, it seems like it's something possible with actions, as mentioned in the issue

**Comment by xafn** [comment]
Settled on using Cloudflare Pages for hosting as it is does not have the issues with Spheron, proper free-tier teams, and PR deployments.
