### ISSUE TITLE
fix: prevent access without authorization token to `/poll`

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/revanced-website#71]
## Issue

Currently, https://revanced.app/poll can be visited without providing any access token.

## Solution

Prevent access by either returning a custom page explaining, why access is denied and how to gain access, redirect to main page or return an error page with code 401.

**Comment by Axelen123** [comment]
I do not see why this is a problem right now, since I doubt anyone will navigate there without a token from the bot.

**Comment by oSumAtrIX** [comment]
The website currently does not have any relationship with Discord or the bot. Anyone can issue a token to acess that page. As an example, the token could be issued over Telegram or Google and so on. The website is only aware of that it needs a token. For that reason it should also handle the case when no token is provided, regardless of where this token has been issued (because it doesn't matter for the page).

**Comment by Axelen123** [comment]
https://github.com/revanced/revanced-website/commit/575ea74ab504ed839c93fdc0a799b36a435eb5a7
