### ISSUE TITLE
fix: prevent poll submission, when there is no selection  

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/revanced-website#72]
## Issue

Currently, you can press the "Submit" button even when there is no selection.

## Solution

Disable the "Submit" button, when there is no selection or round-robin, until at least a selection was made when the end was reached.

**Comment by Axelen123** [comment]
github didnt close this for some reason...

**Comment by Ushie** [comment]
> github didnt close this for some reason...

I think it only does when it ends up in the main branch

**Comment by Axelen123** [comment]
> > github didnt close this for some reason...
> 
> I think it only does when it ends up in the main branch

guhhhh
