### ISSUE TITLE
fix: UI/UX consistency and features

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/revanced-website#73]
### `/poll` page

1. [x] The page currently features multiple buttons with the wrong purpose or inconsistent design:

   1. How does this work?
   3. Clear all
   4. Previous/Next

2. [x] The favicon does not follow the current [branding guidelines](https://github.com/revanced/revanced-branding)
3. [ ] UI suggests that the submitted logo can be clicked on (when there are multiple logos), this does not work on submissions that only have one logo, causing unwanted UX
4. [x] Submitted logos load longer than it should be necessary

## Solutions

1. All buttons should follow the same design. The first button should not be a button in terms of UX but rather a label or similar
2. Follow the guideline with the provided [shape](https://github.com/revanced/revanced-branding/blob/main/assets/revanced-logo/revanced-logo-shape.svg)
3. Introduce a button to open the logo variants popup, standardize clicking on the logo to open a full view at all times
4. Optimize image for web & prefetch/preload images

**Comment by Axelen123** [comment]
FYI: We already prefetch the images and we cannot perform other optimizations on the frontend.

**Comment by Axelen123** [comment]
@xafn what do you think about this?

**Comment by oSumAtrIX** [comment]
> FYI: We already prefetch the images and we cannot perform other optimizations on the frontend.

It looks like the requests are made synchronously. Also they are not prefetched:

![Waterfall](https://user-images.githubusercontent.com/13122796/221032512-b8eea8c9-1f87-4bf7-a5e1-6465dac2edb4.png)

**Comment by xafn** [comment]
1. Yes, that is true. The buttons should be more consistent for better UX. Will probably turn the `How does this work?` button into a `?` icon button appearing in the top right. 
2. Right, will fix.
3. Well, for logos with multiple variants, the review selection is meant to be there for the user to review if they like the logos they chose. If they don't, they click on the variant to unselect it from the pop-up. And with logos with one variant, you click on it to unselect. I do agree with the button to open the pop-up.
4. I have no idea how to speed up the process of fetching the images. Can this even be done asynchronously?

**Comment by oSumAtrIX** [comment]
3. Currently clicking on the logo triggers the popup to select variants (triggered by clicking on the card itself). Apart from the cards rotating through the variants, there is no distinction between a submission with one image and a submission with multiple images. Consider the following scenario: There is a submission. This submission has multiple variants one of which looks pretty cool to you. Since there is no indication that there are multiple variants to that submission you miss it because you didn't know there were variants to it. To solve this issue, the card has to include some kind of indicator such as a button "Show variants" or a label indicating there are multiple so that UX does not suffer.

**Comment by Axelen123** [comment]
4. I'm guessing browsers don't see a benefit in sending several requests at the same time, which makes sense because they are all going to the same destination server. I believe it is better and simpler to just use image tags and let the browser optimize those requests as it sees fit.

**Comment by oSumAtrIX** [comment]
@Axelen123 The images are unoptimized for web, as in them being too large or uncompressed which have a toll on speed.

**Comment by Axelen123** [comment]
> @Axelen123 The images are unoptimized for web, as in them being too large or uncompressed which have a toll on speed.

Network requests dont block the main thread and there is nothing we can do on the frontend about them being unoptimized.

**Comment by xafn** [comment]
![image](https://user-images.githubusercontent.com/47723802/226147643-3447fa0d-f686-49d1-ab50-ac0832d29a3f.png)
yop

**Comment by Axelen123** [comment]
:holy_shit:
