### ISSUE TITLE
Revanced apk download link url is wrong on production (404)

### ISSUE THREAD

**Issue by aqoraan** [revanced/revanced-website#79]
Revanced apk download link url is wrong on production (404)
The current URL:
https://github.com/j-hc/revanced-magisk-module/releases/download/20220857/youtube-revanced-v18.05.40-all.apk
While it should be:
https://github.com/j-hc/revanced-magisk-module/releases/download/20220858/youtube-revanced-v18.05.40-all.apk

**Comment by oSumAtrIX** [comment]
[revanced.app](revanced.app) does not provide download links.
