### ISSUE TITLE
The website title is misspelled

### ISSUE THREAD

**Issue by duckyondiscord** [revanced/revanced-website#82]
Its title is "Continuing the **legecy** of vanced", it should be " Continuing the legacy of vanced"

**Comment by xafn** [comment]
Don't know where you're looking..

![image](https://github.com/revanced/revanced-website/assets/47723802/4fc41ec0-de22-480e-ae24-9b60b50fd06d)
![image](https://github.com/revanced/revanced-website/assets/47723802/f075524a-6b90-4675-b5a6-4c48caeed2f8)

**Comment by duckyondiscord** [comment]
> Don't know where you're looking..
> 
> ![image](https://user-images.githubusercontent.com/47723802/239711728-4fc41ec0-de22-480e-ae24-9b60b50fd06d.png) ![image](https://user-images.githubusercontent.com/47723802/239711724-f075524a-6b90-4675-b5a6-4c48caeed2f8.png)

![image](https://github.com/revanced/revanced-website/assets/94759537/19daed6c-bfbf-4108-a33b-25e080d73209)
Every search engine I try searching for ReVanced with indexes it like this, sorry for the false report.

**Comment by Ushie** [comment]
revanced.io is a fake website, it's not ours
