### ISSUE TITLE
fix: Publishing Source Link Navigation

### ISSUE THREAD

**Issue by bharathkalyans** [revanced/revanced-website#85]
* The publishing link in the [revanced/revanced-website](https://github.com/revanced/revanced-website) is directed to the GitHub repository instead of the revanced website [revanced.io](https://revanced.io/)
* Same goes with the Vanced Logo as well (on the organization README page), it is directed to the repository instead of website.

https://github.com/revanced/revanced-website/assets/49526472/300b5abf-1af3-4caf-8ab5-94d35757fd3f

<img width="1440" alt="Screenshot 2023-05-21 at 8 42 35 PM" src="https://github.com/revanced/revanced-website/assets/49526472/0ca78580-bfc9-4ccf-8b26-e023af235ca3">

_Please do close this issue if it is supposed to be that way_

**Comment by Julius8900** [comment]
revanced.io is a fake ReVanced website.

**Comment by bharathkalyans** [comment]
> revanced.io is a fake ReVanced website.

So you don't want users to be directed to the original website?

**Comment by oSumAtrIX** [comment]
The website is not from us.

**Comment by bharathkalyans** [comment]
> The website is not from us.

So this revanced repository is not the original one? Is it your side project?

**Comment by oSumAtrIX** [comment]
This repository is the original one, anyways this issue is resolved.
