### ISSUE TITLE
Multiple websites

### ISSUE THREAD

**Issue by 3nigm4** [revanced/revanced-website#86]
When searching google I get multiple websites and I am really confused, which one is actually the one that represents the project. Feels like someone wants to get some malware installed by hijacking the projects name and in this way damage the reputation of revanced. Anyway, here are the links that I got today: Maybe clarify where to obtain what and who is behind what, at least from your side. 

https://revanced.net/
https://revanced.org/
https://revanced.app/
https://revanced.io/youtube/

**Comment by reisxd** [comment]
Only https://revanced.app is official.

**Comment by reisxd** [comment]
The site is not done yet, so it redirects to the GitHub page. Also, the official site is mentioned in GitHub

**Comment by 3nigm4** [comment]
Well, I tried.
