### ISSUE TITLE
Add app name to package name in list

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-website#87]
It would be useful to add the App name in parenthesis beside the package name in the list. Or at least the app name at the top of the selected application patches list.

![Screenshot_20230605_225952_Chrome.jpg](https://github.com/revanced/revanced-website/assets/84587632/32691c9d-0dd7-4cd3-98df-1d94cc7a1486)

**Comment by Ushie** [comment]
The website currently has no way whatsoever of getting the App Name, all the information is served by what's available in the ReVanced Patches repository

**Comment by oSumAtrIX** [comment]
This does not work without hardcoding the names. The only way to get names to show up there would be to dynamically resolve them via some API, for example, Google Play Store. Though may be against their ToS and also some apps are not available there.

**Comment by KobeW50** [comment]
Would it be possible to add them manually to the patches repository (and then from there to the site and manager)?

**Comment by oSumAtrIX** [comment]
The app name has no function for patches. Therefor adding it there would be wrong.

**Comment by Ushie** [comment]
Depends on https://github.com/ReVanced/revanced-api/issues/11

**Comment by agamswaroop619** [comment]
Hey @Ushie ,
I am no expert here to say but I think you can create a json file with names of site and their package name for this issue. This could be temporary fix which I can do.

However a permanent solution requires the json file sent by api to have another property to name things and then use this on the to display names

**Comment by oSumAtrIX** [comment]
@agamswaroop619 check the link in the previous comment

**Comment by oSumAtrIX** [comment]
Closing as stale. Create a new issue if necessary.
