### ISSUE TITLE
YTM patch showing mismatching target version

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-website#88]
It does not appear to be synced to the patches repository. Maybe it's synced to a different branch? I didn't bother checking tbh

Edit: It does not appear to be synced to the README in the patches repository.

![SmartSelect_20230605_230317_Chrome.jpg](https://github.com/revanced/revanced-website/assets/84587632/8622fe7e-3bf4-411f-af72-d4f85bf59aaa)

![SmartSelect_20230605_230328_GitHub.jpg](https://github.com/revanced/revanced-website/assets/84587632/b4bddc3b-ce18-4b16-a255-13aaf400c30f)

**Comment by xafn** [comment]
Ah I see the issue, the website takes in the most recent version while the patches README checks the most common version. Will update.

**Comment by Ushie** [comment]
Are you sure it's not the opposite way around? the README shows the latest version for that specific patch, nowhere in the README is the most common version shown

**Comment by xafn** [comment]
Well website for sure shows the most recent version I know that, but I don't know about the README, I was looking into it here: https://github.com/revanced/revanced-patches/blob/5e4ce32ab5b59e5e2f0a1f2472f8238f655b2032/src/main/kotlin/app/revanced/meta/ReadmeGenerator.kt#L33-L36

**Comment by Ushie** [comment]
Wow, this whole time I thought it was just the latest supported for that patch, that makes no sense, it shouldnt be shown on each singular patch if that's a common version for the entire package

**Comment by KobeW50** [comment]
Can this be marked as completed?

**Comment by oSumAtrIX** [comment]
> Wow, this whole time I thought it was just the latest supported for that patch, that makes no sense, it shouldnt be shown on each singular patch if that's a common version for the entire package

Probably should show all compatible versions, if there's too many, it should show an "expand" button.

**Comment by xafn** [comment]
> > Wow, this whole time I thought it was just the latest supported for that patch, that makes no sense, it shouldnt be shown on each singular patch if that's a common version for the entire package
> 
> Probably should show all compatible versions, if there's too many, it should show an "expand" button.

Maybe on click, it presents a modal with all compatible versions?

**Comment by oSumAtrIX** [comment]
Works for me, although a modal will be annoying to dismiss everytime you scroll through the patches.

**Comment by xafn** [comment]
> Works for me, although a modal will be annoying to dismiss everytime you scroll through the patches.

Would be on click on the target version chip.

**Comment by oSumAtrIX** [comment]
A visual clue will definitely help yeah

**Comment by Ushie** [comment]
Yea a simple "More" arrow would portray that
