### ISSUE TITLE
Sidebar doesn't open in kiwi browser

### ISSUE THREAD

**Issue by luimu64** [ReVanced/revanced-website#89]
Tapping the burger menu icon does nothing. Tried disabling dark reader and ublock with no difference. Tried on firefox where it works flawlessly. Following errors show up on page load:
![Screenshot_20230606-064527_Kiwi Browser](https://github.com/revanced/revanced-website/assets/54173370/ff518358-414b-4bb9-b0f1-56051e2c4d01)

**Comment by PalmDevs** [comment]
@oSumAtrIX @xafn You think this is related to the other guy?

**Comment by SystaxError** [comment]
+ brave

**Comment by zalnaRs** [comment]
This is a browser or network issue we can't do anything about this really
