### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by FKXshadow** [revanced/revanced-website#96]
![Screenshot_2023-06-06-09-02-04-20_d365b52accad0f47adbc08c16219827d.jpg](https://github.com/revanced/revanced-website/assets/83650658/404fe5ea-86dc-410a-a189-e66ff9a8a44c)

**Comment by xafn** [comment]
Duplicate of #95

**Comment by oSumAtrIX** [comment]
Currently an issue with deployment and outside of our reach, probably have to wait some minutes

**Comment by FKXshadow** [comment]
Sure, I'll wait. Just wanted the developers to know about it.
