### ISSUE TITLE
HTTP ERROR 404

### ISSUE THREAD

**Issue by Yugorav79** [revanced/revanced-website#97]
![Screenshot_20230606_081025_Chrome](https://github.com/revanced/revanced-website/assets/95852811/d778ceb7-a8fc-4c84-a9a9-06e4face481a)

When I try to access via this link http://revanced.app it shows error 404

**Comment by Julius8900** [comment]
Another duplicate of [#95](https://github.com/revanced/revanced-website/issues/95)

**Comment by Ushie** [comment]
Fixed, should be working for everybody in the following hour
